"""Add pipeline fields to CrawlerTask

Revision ID: 1cdd213ebe94
Revises: cc54c0f8c8b2
Create Date: 2026-01-13 07:00:06.312703

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1cdd213ebe94'
down_revision = 'cc54c0f8c8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawler_task', sa.Column('pipeline_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('crawler_task', sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawler_task', 'current_phase')
    op.drop_column('crawler_task', 'pipeline_state')
    # ### end Alembic commands ###
