"""Add ChatMessage model

Revision ID: 7c7e65ed69c2
Revises: 0d18e8555cbb
Create Date: 2026-01-12 03:53:57.130659

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7c7e65ed69c2'
down_revision = '0d18e8555cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
