"""Add CrawlIndex table

Revision ID: 88159d9cb7aa
Revises: 87f412d380a6
Create Date: 2026-01-14 15:32:34.475124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '88159d9cb7aa'
down_revision = '87f412d380a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_index',
    sa.Column('url_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('content_md5', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_index(op.f('ix_crawl_index_content_md5'), 'crawl_index', ['content_md5'], unique=False)
    op.create_index(op.f('ix_crawl_index_url_hash'), 'crawl_index', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_index_url_hash'), table_name='crawl_index')
    op.drop_index(op.f('ix_crawl_index_content_md5'), table_name='crawl_index')
    op.drop_table('crawl_index')
    # ### end Alembic commands ###
