/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make changes to this file.
// Regenerate it by running `npm run dev` or `npm run build`.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCrawlerAutoRouteImport } from './routes/_layout/crawler/auto'
import { Route as LayoutCrawlerManualRouteImport } from './routes/_layout/crawler/manual'
import { Route as LayoutCrawlerIndustrialRouteImport } from './routes/_layout/crawler/industrial'

const SignupRoute = SignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
    id: '/recover-password',
    path: '/recover-password',
    getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrawlerAutoRoute = LayoutCrawlerAutoRouteImport.update({
    id: '/crawler/auto',
    path: '/crawler/auto',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrawlerManualRoute = LayoutCrawlerManualRouteImport.update({
    id: '/crawler/manual',
    path: '/crawler/manual',
    getParentRoute: () => LayoutRoute,
} as any)
const LayoutCrawlerIndustrialRoute = LayoutCrawlerIndustrialRouteImport.update({
    id: '/crawler/industrial',
    path: '/crawler/industrial',
    getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
    '/login': typeof LoginRoute
    '/recover-password': typeof RecoverPasswordRoute
    '/reset-password': typeof ResetPasswordRoute
    '/signup': typeof SignupRoute
    '/admin': typeof LayoutAdminRoute
    '/chat': typeof LayoutChatRoute
    '/items': typeof LayoutItemsRoute
    '/settings': typeof LayoutSettingsRoute
    '/': typeof LayoutIndexRoute
    '/crawler/auto': typeof LayoutCrawlerAutoRoute
    '/crawler/manual': typeof LayoutCrawlerManualRoute
    '/crawler/industrial': typeof LayoutCrawlerIndustrialRoute
}
export interface FileRoutesByTo {
    '/login': typeof LoginRoute
    '/recover-password': typeof RecoverPasswordRoute
    '/reset-password': typeof ResetPasswordRoute
    '/signup': typeof SignupRoute
    '/admin': typeof LayoutAdminRoute
    '/chat': typeof LayoutChatRoute
    '/items': typeof LayoutItemsRoute
    '/settings': typeof LayoutSettingsRoute
    '/': typeof LayoutIndexRoute
    '/crawler/auto': typeof LayoutCrawlerAutoRoute
    '/crawler/manual': typeof LayoutCrawlerManualRoute
    '/crawler/industrial': typeof LayoutCrawlerIndustrialRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/_layout': typeof LayoutRouteWithChildren
    '/login': typeof LoginRoute
    '/recover-password': typeof RecoverPasswordRoute
    '/reset-password': typeof ResetPasswordRoute
    '/signup': typeof SignupRoute
    '/_layout/admin': typeof LayoutAdminRoute
    '/_layout/chat': typeof LayoutChatRoute
    '/_layout/items': typeof LayoutItemsRoute
    '/_layout/settings': typeof LayoutSettingsRoute
    '/_layout/': typeof LayoutIndexRoute
    '/_layout/crawler/auto': typeof LayoutCrawlerAutoRoute
    '/_layout/crawler/manual': typeof LayoutCrawlerManualRoute
    '/_layout/crawler/industrial': typeof LayoutCrawlerIndustrialRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/items'
    | '/settings'
    | '/'
    | '/crawler/auto'
    | '/crawler/manual'
    | '/crawler/industrial'
    fileRoutesByTo: FileRoutesByTo
    to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/items'
    | '/settings'
    | '/'
    | '/crawler/auto'
    | '/crawler/manual'
    | '/crawler/industrial'
    id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/crawler/auto'
    | '/_layout/crawler/manual'
    | '/_layout/crawler/industrial'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    LayoutRoute: typeof LayoutRouteWithChildren
    LoginRoute: typeof LoginRoute
    RecoverPasswordRoute: typeof RecoverPasswordRoute
    ResetPasswordRoute: typeof ResetPasswordRoute
    SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/signup': {
            id: '/signup'
            path: '/signup'
            fullPath: '/signup'
            preLoaderRoute: typeof SignupRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/reset-password': {
            id: '/reset-password'
            path: '/reset-password'
            fullPath: '/reset-password'
            preLoaderRoute: typeof ResetPasswordRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/recover-password': {
            id: '/recover-password'
            path: '/recover-password'
            fullPath: '/recover-password'
            preLoaderRoute: typeof RecoverPasswordRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/login': {
            id: '/login'
            path: '/login'
            fullPath: '/login'
            preLoaderRoute: typeof LoginRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/_layout': {
            id: '/_layout'
            path: ''
            fullPath: ''
            preLoaderRoute: typeof LayoutRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/_layout/': {
            id: '/_layout/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof LayoutIndexRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/settings': {
            id: '/_layout/settings'
            path: '/settings'
            fullPath: '/settings'
            preLoaderRoute: typeof LayoutSettingsRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/items': {
            id: '/_layout/items'
            path: '/items'
            fullPath: '/items'
            preLoaderRoute: typeof LayoutItemsRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/chat': {
            id: '/_layout/chat'
            path: '/chat'
            fullPath: '/chat'
            preLoaderRoute: typeof LayoutChatRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/admin': {
            id: '/_layout/admin'
            path: '/admin'
            fullPath: '/admin'
            preLoaderRoute: typeof LayoutAdminRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/crawler/auto': {
            id: '/_layout/crawler/auto'
            path: '/crawler/auto'
            fullPath: '/crawler/auto'
            preLoaderRoute: typeof LayoutCrawlerAutoRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/crawler/manual': {
            id: '/_layout/crawler/manual'
            path: '/crawler/manual'
            fullPath: '/crawler/manual'
            preLoaderRoute: typeof LayoutCrawlerManualRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/_layout/crawler/industrial': {
            id: '/_layout/crawler/industrial'
            path: '/crawler/industrial'
            fullPath: '/crawler/industrial'
            preLoaderRoute: typeof LayoutCrawlerIndustrialRouteImport
            parentRoute: typeof LayoutRoute
        }
    }
}

interface LayoutRouteChildren {
    LayoutAdminRoute: typeof LayoutAdminRoute
    LayoutChatRoute: typeof LayoutChatRoute
    LayoutItemsRoute: typeof LayoutItemsRoute
    LayoutSettingsRoute: typeof LayoutSettingsRoute
    LayoutIndexRoute: typeof LayoutIndexRoute
    LayoutCrawlerAutoRoute: typeof LayoutCrawlerAutoRoute
    LayoutCrawlerManualRoute: typeof LayoutCrawlerManualRoute
    LayoutCrawlerIndustrialRoute: typeof LayoutCrawlerIndustrialRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
    LayoutAdminRoute: LayoutAdminRoute,
    LayoutChatRoute: LayoutChatRoute,
    LayoutItemsRoute: LayoutItemsRoute,
    LayoutSettingsRoute: LayoutSettingsRoute,
    LayoutIndexRoute: LayoutIndexRoute,
    LayoutCrawlerAutoRoute: LayoutCrawlerAutoRoute,
    LayoutCrawlerManualRoute: LayoutCrawlerManualRoute,
    LayoutCrawlerIndustrialRoute: LayoutCrawlerIndustrialRoute,
}

const LayoutRouteWithChildren =
    LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
    LayoutRoute: LayoutRouteWithChildren,
    LoginRoute: LoginRoute,
    RecoverPasswordRoute: RecoverPasswordRoute,
    ResetPasswordRoute: ResetPasswordRoute,
    SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()
